### ISSUE TITLE
How can I get the data set, such as hdm05-122

### ISSUE THREAD

**Issue by lyhisme** [fabiocarrara/mocap#1]

**Comment by fabiocarrara** [comment]
The complete dataset can be found here:
http://resources.mpi-inf.mpg.de/HDM05/

Drop me an email if you are interested in already-parsed files that are compatible with our implementation.

**Comment by lyhisme** [comment]
Thank you very much for answering my question.
And I have written an email about the specific content.

**Comment by fabiocarrara** [comment]
Info for getting the dataset is now provided in the README.
